name: tagged_field
description: "Flutter TextField with tag autocomplete and chip visualization"
version: 1.0.2
homepage: https://github.com/yender112/tagged_field
repository: https://github.com/yender112/tagged_field
issue_tracker: https://github.com/yender112/tagged_field/issues
publish_to: none

topics:
  - textfield
  - keyvalue
  - tags
  - filters
  - autocomplete

platforms:
  android:
  ios:
  web:
  macos:

environment:
  sdk: ^3.10.0
  flutter: ">=3.35.7"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
